# Generated by Django 3.2.16 on 2022-11-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
