# Generated by Django 4.1.2 on 2022-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0002_customer_avatar_customer_date_created_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='prof.png', null=True, upload_to=''),
        ),
    ]
