# Generated by Django 4.1.2 on 2022-11-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0002_customer_order_shippingaddress_orderitem'),
        ('lexiconapp', '0003_rename_userprofileinfo_user'),
    ]

    operations = [
    ]
