# Generated by Django 4.1.2 on 2022-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0003_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='prof.png', upload_to='profile_pics'),
        ),
    ]
