# Generated by Django 3.2.16 on 2022-11-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
