# Generated by Django 3.2.16 on 2022-11-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
