# Generated by Django 4.1.2 on 2022-11-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0004_merge_20221116_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
